version: '3'
services:
  influxdb:
    image: influxdb
    container_name: influxdb
    ports:
      - '8086:8086'
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=password
      - DOCKER_INFLUXDB_INIT_ORG=myorg
      - DOCKER_INFLUXDB_INIT_BUCKET=mybucket

  flask-api:
    build: ./flask-api
    container_name: flask-api
    environment:
      - INFLUXDB_NAME=mydatabase
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ORG=myorg
      - INFLUXDB_BUCKET=somebucket
      - INFLUXDB_ADMIN_PASSWORD=password
      - INFLUXDB_HOST=influxdb
    ports:
      - '5000:5000'
    depends_on:
      - influxdb

  react_app:
    build: ./react_app
    container_name: react_app
    ports:
      - '3000:3000'
    depends_on:
      - flask-api

  data-generator:
    build: ./data-generator
    container_name: data-generator
    depends_on:
      - influxdb
    environment:
      - INFLUXDB_NAME=mydatabase
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ORG=myorg
      - INFLUXDB_BUCKET=somebucket
      - INFLUXDB_ADMIN_PASSWORD=password
      - INFLUXDB_HOST=influxdb
    command: python data_generator.py